# Generated by Django 3.1.1 on 2020-10-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPanneReparation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparation',
            name='prix_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reparation',
            name='tva',
            field=models.FloatField(default=0.0),
        ),
    ]
