# Generated by Django 3.1.1 on 2020-10-17 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GPanneReparation', '0002_auto_20201017_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
