# Generated by Django 3.1.1 on 2020-10-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPanneReparation', '0002_auto_20201031_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation',
            name='prix_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='tva',
            field=models.FloatField(),
        ),
    ]
