# Generated by Django 3.1.1 on 2020-10-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPanneReparation', '0003_auto_20201017_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='pieces',
            field=models.ManyToManyField(blank=True, to='GPanneReparation.Piece'),
        ),
    ]
