# Generated by Django 3.1.1 on 2020-10-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPanneReparation', '0003_auto_20201031_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation',
            name='prix_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='tva',
            field=models.FloatField(default=0.0),
        ),
    ]
