# Generated by Django 3.1.1 on 2020-10-26 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GInterventionReclamation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GProduit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention_interne',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention_externe',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GProduit.tier'),
        ),
    ]
