# Generated by Django 3.1.1 on 2020-10-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GInterventionReclamation', '0002_auto_20201016_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='etat',
            field=models.CharField(choices=[(1, 'En attente'), (2, 'En cours de traitement'), (3, 'Clôturée')], default=1, max_length=1),
        ),
    ]
