# Generated by Django 3.1.1 on 2020-10-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GInterventionReclamation', '0003_auto_20201016_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='etat',
            field=models.CharField(choices=[('0', 'En attente'), ('1', 'En cours de traitement'), ('2', 'Clôturée')], default=1, max_length=1),
        ),
    ]
