# Generated by Django 3.1.1 on 2020-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GProduit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='prix_total',
            field=models.FloatField(default=0.0),
        ),
    ]
