# Generated by Django 3.1.1 on 2020-10-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GProduit', '0002_auto_20201016_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type',
            field=models.CharField(choices=[('0', 'Achat'), ('1', 'Réparation'), ('2', 'Achat et réparation')], default=1, max_length=1),
        ),
    ]
