# Generated by Django 3.1.1 on 2020-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GProduit', '0003_auto_20201016_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat_produit',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_totale',
            field=models.PositiveIntegerField(),
        ),
    ]
